"""empty message

Revision ID: 22b250a4f200
Revises: 6b0fc0dd468
Create Date: 2019-06-25 01:29:17.782735

"""

# revision identifiers, used by Alembic.
revision = '22b250a4f200'
down_revision = '6b0fc0dd468'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('level', sa.Integer(), nullable=False))
    op.add_column('categories', sa.Column('lft', sa.Integer(), nullable=False))
    op.add_column('categories', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.add_column('categories', sa.Column('rgt', sa.Integer(), nullable=False))
    op.add_column('categories', sa.Column('tree_id', sa.Integer(), nullable=True))
    op.create_index('categories_level_idx', 'categories', ['level'], unique=False)
    op.create_index('categories_lft_idx', 'categories', ['lft'], unique=False)
    op.create_index('categories_rgt_idx', 'categories', ['rgt'], unique=False)
    op.create_unique_constraint(None, 'categories', ['id'])
    op.create_foreign_key(None, 'categories', 'categories', ['parent_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(None, 'layout_discuss', ['id'])
    op.create_unique_constraint(None, 'layout_discuss_objects', ['id'])
    op.drop_constraint(u'layout_discuss_objects_layout_discuss_id_fkey', 'layout_discuss_objects', type_='foreignkey')
    op.create_foreign_key(None, 'layout_discuss_objects', 'layout_discuss', ['layout_discuss_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(None, 'layout_protos', ['id'])
    op.create_unique_constraint(None, 'layout_users', ['id'])
    op.drop_constraint(u'layout_users_layout_id_fkey', 'layout_users', type_='foreignkey')
    op.create_foreign_key(None, 'layout_users', 'layouts', ['layout_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(None, 'layout_users_access', ['id'])
    op.create_unique_constraint(None, 'layouts', ['id'])
    op.create_unique_constraint(None, 'objects', ['id'])
    op.create_unique_constraint(None, 'objects_categories', ['id'])
    op.drop_constraint(u'objects_categories_object_id_fkey', 'objects_categories', type_='foreignkey')
    op.create_foreign_key(None, 'objects_categories', 'objects', ['object_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(None, 'proto_objects', ['id'])
    op.create_unique_constraint(None, 'prototypes', ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'prototypes', type_='unique')
    op.drop_constraint(None, 'proto_objects', type_='unique')
    op.drop_constraint(None, 'objects_categories', type_='foreignkey')
    op.create_foreign_key(u'objects_categories_object_id_fkey', 'objects_categories', 'categories', ['object_id'], ['id'], ondelete=u'CASCADE')
    op.drop_constraint(None, 'objects_categories', type_='unique')
    op.drop_constraint(None, 'objects', type_='unique')
    op.drop_constraint(None, 'layouts', type_='unique')
    op.drop_constraint(None, 'layout_users_access', type_='unique')
    op.drop_constraint(None, 'layout_users', type_='foreignkey')
    op.create_foreign_key(u'layout_users_layout_id_fkey', 'layout_users', 'proto_objects', ['layout_id'], ['id'], ondelete=u'CASCADE')
    op.drop_constraint(None, 'layout_users', type_='unique')
    op.drop_constraint(None, 'layout_protos', type_='unique')
    op.drop_constraint(None, 'layout_discuss_objects', type_='foreignkey')
    op.create_foreign_key(u'layout_discuss_objects_layout_discuss_id_fkey', 'layout_discuss_objects', 'layouts', ['layout_discuss_id'], ['id'], ondelete=u'CASCADE')
    op.drop_constraint(None, 'layout_discuss_objects', type_='unique')
    op.drop_constraint(None, 'layout_discuss', type_='unique')
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_constraint(None, 'categories', type_='unique')
    op.drop_index('categories_rgt_idx', table_name='categories')
    op.drop_index('categories_lft_idx', table_name='categories')
    op.drop_index('categories_level_idx', table_name='categories')
    op.drop_column('categories', 'tree_id')
    op.drop_column('categories', 'rgt')
    op.drop_column('categories', 'parent_id')
    op.drop_column('categories', 'lft')
    op.drop_column('categories', 'level')
    ### end Alembic commands ###
